services:
  - type: web
    name: manishas-kitchen
    runtime: node
    plan: free
    buildCommand: npm --prefix server ci --legacy-peer-deps --include=dev && npm --prefix client ci --legacy-peer-deps --include=dev && npm --prefix client run build:only && npm --prefix server run build
    startCommand: npm --prefix server run deploy && npm --prefix server start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: CI
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: manishas-kitchen-db
          property: connectionString

databases:
  - name: manishas-kitchen-db
    databaseName: manishas_kitchen
    plan: free
